// Excalidraw diagram: Email automation workflow
// Inbox → Graph API → Windmill → GPT-4o mini → Digest → WhatsApp

export const emailAutomationElements = [
  // --- Boîte Inbox ---
  {
    id: "inbox-box",
    type: "rectangle",
    x: 20, y: 140, width: 140, height: 70,
    strokeColor: "#6366f1", backgroundColor: "#1e1b4b",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [{ id: "arrow1", type: "arrow" }], updated: 1, version: 1, versionNonce: 10,
    isDeleted: false, link: null, locked: false,
  },
  {
    id: "inbox-label",
    type: "text",
    x: 30, y: 158, width: 120, height: 36,
    text: "📧 Boîte mail\n(Outlook / IMAP)",
    fontSize: 13, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#a5b4fc", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 11,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "📧 Boîte mail\n(Outlook / IMAP)",
  },

  // --- Arrow 1: Inbox → Graph API ---
  {
    id: "arrow1",
    type: "arrow",
    x: 162, y: 175, width: 68, height: 0,
    strokeColor: "#6b7280", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    startArrowhead: null, endArrowhead: "arrow",
    points: [[0, 0], [68, 0]],
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 20,
    isDeleted: false, link: null, locked: false,
    startBinding: { elementId: "inbox-box", focus: 0, gap: 2 },
    endBinding: { elementId: "graphapi-box", focus: 0, gap: 2 },
  },
  {
    id: "arrow1-label",
    type: "text",
    x: 173, y: 157, width: 46, height: 16,
    text: "fetch",
    fontSize: 11, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#6b7280", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 21,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "fetch",
  },

  // --- Boîte Graph API ---
  {
    id: "graphapi-box",
    type: "rectangle",
    x: 230, y: 140, width: 140, height: 70,
    strokeColor: "#0078d4", backgroundColor: "#1e3a5f",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [{ id: "arrow2", type: "arrow" }], updated: 1, version: 1, versionNonce: 30,
    isDeleted: false, link: null, locked: false,
  },
  {
    id: "graphapi-label",
    type: "text",
    x: 240, y: 158, width: 120, height: 36,
    text: "🔵 Microsoft\nGraph API",
    fontSize: 13, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#60a5fa", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 31,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "🔵 Microsoft\nGraph API",
  },

  // --- Arrow 2: Graph API → Windmill ---
  {
    id: "arrow2",
    type: "arrow",
    x: 372, y: 175, width: 68, height: 0,
    strokeColor: "#6b7280", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    startArrowhead: null, endArrowhead: "arrow",
    points: [[0, 0], [68, 0]],
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 40,
    isDeleted: false, link: null, locked: false,
    startBinding: { elementId: "graphapi-box", focus: 0, gap: 2 },
    endBinding: { elementId: "windmill-box", focus: 0, gap: 2 },
  },
  {
    id: "arrow2-label",
    type: "text",
    x: 383, y: 157, width: 46, height: 16,
    text: "JSON",
    fontSize: 11, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#6b7280", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 41,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "JSON",
  },

  // --- Boîte Windmill ---
  {
    id: "windmill-box",
    type: "rectangle",
    x: 440, y: 130, width: 150, height: 90,
    strokeColor: "#10b981", backgroundColor: "#064e3b",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [{ id: "arrow3", type: "arrow" }], updated: 1, version: 1, versionNonce: 50,
    isDeleted: false, link: null, locked: false,
  },
  {
    id: "windmill-label",
    type: "text",
    x: 450, y: 148, width: 130, height: 56,
    text: "⚙️ Windmill\nPython script\n(filtre + prépa)",
    fontSize: 13, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#6ee7b7", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 51,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "⚙️ Windmill\nPython script\n(filtre + prépa)",
  },

  // --- Arrow 3: Windmill → GPT ---
  {
    id: "arrow3",
    type: "arrow",
    x: 592, y: 175, width: 68, height: 0,
    strokeColor: "#6b7280", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    startArrowhead: null, endArrowhead: "arrow",
    points: [[0, 0], [68, 0]],
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 60,
    isDeleted: false, link: null, locked: false,
    startBinding: { elementId: "windmill-box", focus: 0, gap: 2 },
    endBinding: { elementId: "gpt-box", focus: 0, gap: 2 },
  },
  {
    id: "arrow3-label",
    type: "text",
    x: 600, y: 157, width: 52, height: 16,
    text: "prompt",
    fontSize: 11, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#6b7280", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 61,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "prompt",
  },

  // --- Boîte GPT ---
  {
    id: "gpt-box",
    type: "rectangle",
    x: 660, y: 140, width: 140, height: 70,
    strokeColor: "#f59e0b", backgroundColor: "#451a03",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [{ id: "arrow4", type: "arrow" }], updated: 1, version: 1, versionNonce: 70,
    isDeleted: false, link: null, locked: false,
  },
  {
    id: "gpt-label",
    type: "text",
    x: 670, y: 158, width: 120, height: 36,
    text: "🤖 GPT-4o mini\n(résumé + score)",
    fontSize: 13, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#fcd34d", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 71,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "🤖 GPT-4o mini\n(résumé + score)",
  },

  // --- Arrow 4: GPT → Digest (down) ---
  {
    id: "arrow4",
    type: "arrow",
    x: 730, y: 212, width: 0, height: 58,
    strokeColor: "#6b7280", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    startArrowhead: null, endArrowhead: "arrow",
    points: [[0, 0], [0, 58]],
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 80,
    isDeleted: false, link: null, locked: false,
    startBinding: { elementId: "gpt-box", focus: 0, gap: 2 },
    endBinding: { elementId: "digest-box", focus: 0, gap: 2 },
  },
  {
    id: "arrow4-label",
    type: "text",
    x: 735, y: 232, width: 50, height: 16,
    text: "digest",
    fontSize: 11, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#6b7280", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 81,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "digest",
  },

  // --- Boîte Digest ---
  {
    id: "digest-box",
    type: "rectangle",
    x: 660, y: 270, width: 140, height: 70,
    strokeColor: "#ec4899", backgroundColor: "#4a044e",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 90,
    isDeleted: false, link: null, locked: false,
  },
  {
    id: "digest-label",
    type: "text",
    x: 670, y: 288, width: 120, height: 36,
    text: "📱 Digest\nWhatsApp / Email",
    fontSize: 13, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#f9a8d4", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 91,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "📱 Digest\nWhatsApp / Email",
  },

  // --- Titre du diagramme ---
  {
    id: "title",
    type: "text",
    x: 20, y: 60, width: 780, height: 30,
    text: "Pipeline veille email automatique — 1 fois par jour, zéro intervention",
    fontSize: 16, fontFamily: 1,
    textAlign: "center", verticalAlign: "top",
    strokeColor: "#9ca3af", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 100,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "Pipeline veille email automatique — 1 fois par jour, zéro intervention",
  },
];
