// Excalidraw diagram: Stack architecture David Aames
// OpenClaw → Windmill → APIs → WhatsApp

export const stackArchitectureElements = [
  // --- Boîtes ---
  {
    id: "oc-box",
    type: "rectangle",
    x: 40, y: 150, width: 160, height: 80,
    strokeColor: "#10b981", backgroundColor: "#064e3b",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 1,
    isDeleted: false, link: null, locked: false,
  },
  {
    id: "oc-label",
    type: "text",
    x: 55, y: 168, width: 130, height: 46,
    text: "🤖 OpenClaw\nAgent IA",
    fontSize: 16, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#ffffff", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 2,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "🤖 OpenClaw\nAgent IA",
  },

  // Windmill
  {
    id: "wm-box",
    type: "rectangle",
    x: 280, y: 150, width: 160, height: 80,
    strokeColor: "#3b82f6", backgroundColor: "#1e3a5f",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 3,
    isDeleted: false, link: null, locked: false,
  },
  {
    id: "wm-label",
    type: "text",
    x: 295, y: 168, width: 130, height: 46,
    text: "⚙️ Windmill\nOrchestration",
    fontSize: 16, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#ffffff", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 4,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "⚙️ Windmill\nOrchestration",
  },

  // APIs
  {
    id: "api-box",
    type: "rectangle",
    x: 520, y: 80, width: 160, height: 80,
    strokeColor: "#8b5cf6", backgroundColor: "#2e1065",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 5,
    isDeleted: false, link: null, locked: false,
  },
  {
    id: "api-label",
    type: "text",
    x: 535, y: 98, width: 130, height: 46,
    text: "🌐 APIs externes\nGraph, Umami…",
    fontSize: 14, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#ffffff", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 6,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "🌐 APIs externes\nGraph, Umami…",
  },

  // WhatsApp
  {
    id: "wa-box",
    type: "rectangle",
    x: 520, y: 240, width: 160, height: 80,
    strokeColor: "#10b981", backgroundColor: "#064e3b",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 7,
    isDeleted: false, link: null, locked: false,
  },
  {
    id: "wa-label",
    type: "text",
    x: 535, y: 258, width: 130, height: 46,
    text: "📱 WhatsApp\nErwan",
    fontSize: 16, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#ffffff", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 8,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "📱 WhatsApp\nErwan",
  },

  // --- Flèches ---
  // OC → WM
  {
    id: "arr-oc-wm",
    type: "arrow",
    x: 200, y: 190, width: 80, height: 0,
    strokeColor: "#6b7280", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    startBinding: { elementId: "oc-box", focus: 0, gap: 1 },
    endBinding: { elementId: "wm-box", focus: 0, gap: 1 },
    points: [[0, 0], [80, 0]],
    lastCommittedPoint: null, startArrowhead: null, endArrowhead: "arrow",
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 9,
    isDeleted: false, link: null, locked: false,
  },
  // WM → API
  {
    id: "arr-wm-api",
    type: "arrow",
    x: 440, y: 170, width: 80, height: -50,
    strokeColor: "#6b7280", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    startBinding: null, endBinding: null,
    points: [[0, 0], [80, -50]],
    lastCommittedPoint: null, startArrowhead: null, endArrowhead: "arrow",
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 10,
    isDeleted: false, link: null, locked: false,
  },
  // WM → WA (via OC)
  {
    id: "arr-wm-wa",
    type: "arrow",
    x: 440, y: 210, width: 80, height: 70,
    strokeColor: "#6b7280", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 2, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    startBinding: null, endBinding: null,
    points: [[0, 0], [80, 70]],
    lastCommittedPoint: null, startArrowhead: null, endArrowhead: "arrow",
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 11,
    isDeleted: false, link: null, locked: false,
  },

  // Labels flèches
  {
    id: "lbl-trigger",
    type: "text",
    x: 218, y: 172, width: 64, height: 20,
    text: "déclenche",
    fontSize: 12, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#9ca3af", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 12,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "déclenche",
  },
  {
    id: "lbl-alerte",
    type: "text",
    x: 455, y: 255, width: 50, height: 20,
    text: "alerte",
    fontSize: 12, fontFamily: 1,
    textAlign: "center", verticalAlign: "middle",
    strokeColor: "#9ca3af", backgroundColor: "transparent",
    fillStyle: "solid", strokeWidth: 1, strokeStyle: "solid",
    roughness: 1, opacity: 100, angle: 0,
    groupIds: [], boundElements: [], updated: 1, version: 1, versionNonce: 13,
    isDeleted: false, link: null, locked: false,
    containerId: null, originalText: "alerte",
  },
] as const;
