// Bash code stored as a regular string to avoid template literal interpolation issues
// with ${#ARRAY[@]} bash syntax
export const SECURITY_CHECK_BASH = [
  "#!/bin/bash",
  "ISSUES=()",
  "THRESHOLD_CPU=80",
  "THRESHOLD_RAM=85",
  "THRESHOLD_DISK=90",
  "",
  "# CPU",
  'CPU=$(top -bn1 | grep "Cpu(s)" | awk \'{print $2}\' | cut -d\'%\' -f1 | cut -d\',\' -f1)',
  '[ "$(echo "$CPU > $THRESHOLD_CPU" | bc -l)" = "1" ] && \\',
  '  ISSUES+=("⚠️ CPU élevé : ${CPU}%")',
  "",
  "# RAM",
  "RAM=$(free | awk '/^Mem/ {printf \"%.0f\", $3/$2*100}')",
  '[ "$RAM" -gt "$THRESHOLD_RAM" ] && \\',
  '  ISSUES+=("⚠️ RAM élevée : ${RAM}%")',
  "",
  "# Disque",
  "DISK=$(df / | awk 'NR==2 {print $5}' | tr -d '%')",
  '[ "$DISK" -gt "$THRESHOLD_DISK" ] && \\',
  '  ISSUES+=("⚠️ Disque plein : ${DISK}%")',
  "",
  "# Docker",
  'STOPPED=$(docker ps -a --filter "status=exited" --format "{{.Names}}" 2>/dev/null)',
  '[ -n "$STOPPED" ] && \\',
  '  ISSUES+=("🐳 Conteneurs arrêtés : $STOPPED")',
  "",
  "# UFW",
  'UFW=$(ufw status | grep -c "Status: active" || true)',
  '[ "$UFW" -eq 0 ] && ISSUES+=("🔓 UFW INACTIF !")',
  "",
  "# Résultat",
  'if [ ${#ISSUES[@]} -eq 0 ]; then',
  "  echo '{\"ok\": true, \"issues\": []}'",
  "else",
  '  printf \'%s\\n\' "${ISSUES[@]}"',
  "  exit 1",
  "fi",
].join("\n");
